CREATE TABLE AuditLog(LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,TransactionID NUMBER,AccountID NUMBER,Amount NUMBER,TransactionType VARCHAR2(20),LogDate DATE);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
Begin
    insert into AuditLog(TransactionID,AccountID,Amount,TransactionType,LogDate)values(:NEW.TransactionID,:NEW.AccountID,:NEW.Amount,:NEW.TransactionType,SYSDATE);
End;
/